services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    image: ghcr.io/igorlatii/fastapi-ai:latest
    restart: unless-stopped
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - mysql
    ports:
      - "${FASTAPI_PORT}:8000"

  django:
    image: ghcr.io/igorlatii/django-admin:latest
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "${DJANGO_PORT}:8001"

  bot:
    image: ghcr.io/igorlatii/telegram-bot:latest
    restart: unless-stopped
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_OWNER: ${BOT_OWNER}
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql_data: