services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./initdb/Dump20250413:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  dasi:
    image: ghcr.io/igorlatii/dasi:latest
    restart: unless-stopped
    environment:
      SPRING_MONGODB_URI: mongodb://mongo:27017/dasi
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      EXTERNAL_API_URL: http://fastapi:8000/ask
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      APP_MAIL_FROM: ${APP_MAIL_FROM}
      APP_MAIL_FROM_NAME: ${APP_MAIL_FROM_NAME}
    depends_on:
      - mongo
      - fastapi
    ports:
      - "8082:8080"

  bridge-console:
    image: ghcr.io/igorlatii/bridge-console:latest
    restart: unless-stopped
    depends_on:
      - dasi
    ports:
      - "3001:8080"

  fastapi:
    image: ghcr.io/igorlatii/fastapi-ai:${FASTAPI_IMAGE_TAG}
    restart: unless-stopped
    environment:
      db_host: mysql
      db_port: ${DB_PORT}
      db_name: ${MYSQL_DATABASE}
      db_user: ${MYSQL_USER}
      db_password: ${MYSQL_PASSWORD}
      openai_api_key: ${OPENAI_API_KEY}
    depends_on:
      - mysql
    ports:
      - "${FASTAPI_PORT}:8000"

  django:
    image: ghcr.io/igorlatii/django-admin:${DJANGO_IMAGE_TAG}
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJ_HOST: ${DJ_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - mysql
    ports:
      - "${DJANGO_PORT}:8001"

  bot:
    image: ghcr.io/igorlatii/telegram-bot:${BOT_IMAGE_TAG}
    restart: unless-stopped
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_OWNER: ${BOT_OWNER}
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql_data:
  mongo_data: